version: "3.7"

services:
    nginx:
        volumes:
            - ./lolisafe-data:/usr/lolisafe/uploads

    lolisafe:
        volumes:
            - ./lolisafe-data:/usr/lolisafe/uploads
            - ./lolisafe-database:/usr/lolisafe/database
